C*********************************************************************
        SUBROUTINE RUNRD(NITER,KFYL1,KFYL2)
C*********************************************************************
C
C  ALLEN BECKER ADDED THIS TO READ VALUES OF MOST PARAMETERS FROM FILE 
C  'RUNDAT.DAT'.  THIS REPLACES THE OLD BLOCK DATA FILE.  
C   
C     FLUDWIG REVISED 5/97
C
        INCLUDE 'NGRIDS.PAR'
C
        INCLUDE 'ANCHOR.CMM'
        INCLUDE 'FLOWER.CMM'
        INCLUDE 'LIMITS.CMM'
        INCLUDE 'STALOC.CMM'
C
C  OPEN RUN DESCRIPTORS.
C
C
        OPEN (22,FILE=CHPATH//'RUNSTF'//CHMESH//'.DAT', 
     $			STATUS='UNKNOWN',FORM='FORMATTED')
        READ (22,*)
        READ (22,6002) CHPOUT
	CHPVEX=CHPOUT
	WRITE (*,*) CHPOUT
C
	READ (22,*) DBUG,DBUG2
	READ (22,*) DOBIN,DOFLAT
C
C  READ NUMBER OF VERTICAL FLOW SURFACES 
C
        READ (22,*) NLVL
	IF (NLVL.GT.NZGRD .OR. NLVL .LT. 1) THEN
	   WRITE (*,*) 'BAD NUMBER OF LEVELS', NLVL, NZGRD
	   PAUSE
	   STOP
	END IF
C
C  READ FLOW LEVELS (FRACTION OF TOP LEVEL)
C
        READ(22,*) (SIGMA(K),K=1,NLVL)
	WRITE (*,*) (SIGMA(K),K=1,NLVL)
C
        READ (22,*) NFLAT
	IF (NFLAT.GT.NHORIZ .OR. NFLAT .LT. 1) THEN
	   WRITE (*,*) 'BAD NUMBER OF LEVELS', NHORIZ, NFLAT
	   PAUSE
	   STOP
	END IF
C
C  READ FLOW LEVELS IN M ABOVE LOW POINT
C
        READ(22,*) (ZCHOOZ(K),K=1,NFLAT)
C
C  READ FACTOR FOR CONVERTING TO M/S
C
	READ (22,*) SPDCNV
C
C  READ NO. COLS,ROWS FOR GRID
C
        READ (22,*) NROW,NCOL
	IF (NROW .GT. NYGRD .OR. NCOL .GT. NXGRD) THEN
	   WRITE (*,*) 'BAD X,Y DIMENSIONS ARE ',NCOL,NROW
	   WRITE (*,*) 'THEY SHOULD NOT BE > ', NXGRD,NYGRD
	   PAUSE
	   STOP
	END IF
C
C  READ GRID PT INTERVAL FOR ASCII OUTPUT -- IS ALL
C  GRID PTS, 2, EVRY OTHER ONE ETC.
C
        READ (22,*) NSKIP
        READ (22,*) NRYTX, NRYTY
        READ (22,*) NASCX0, NASCY0
C
C  CHECK FOR OUT-OF-BOUNDS ARRAY STUFF.
C
	IF (NASCX0-1+NRYTX .GT. NCOL) THEN
	   WRITE (*,*) 'WRITE GRID RUNS OVER CALC. GRID -- X DIRECT.'
	   NRYTX=NCOL-NASCX0+1
	   WRITE (*,*) 'NO OF OUTPUT COLUMNS SET TO ',NRYTX
	END IF
	IF (NASCY0-1+NRYTY .GT. NCOL) THEN
	   WRITE (*,*) 'WRITE GRID RUNS OVER CALC. GRID -- Y DIRECT.'
	   NRYTY=NROW-NASCY0+1
	   WRITE (*,*) 'NO OF OUTPUT ROWS SET TO ',NRYTY
	END IF
C
C  READ GRID INTERVALS IN KM
C
        READ (22,*) DSCRS
C
C  READ UTM COORDINATE OF REFERENCE POINT (1,1)--(X,Y) 
C
        READ (22,*) UTMAPX,UTMAPY
	WRITE (*,*) UTMAPX,UTMAPY
C
C  READ ANCHOR POINT GRID INDICES (IX,JY) 
C
        READ (22,*) KGRIDX,KGRIDY
	XORIG=UTMAPX-DSCRS*FLOAT(KGRIDX)
	YORIG=UTMAPY-DSCRS*FLOAT(KGRIDY)
C
C  CONSTANTS USED TO DEFINE SURFACE SHAPES SUBROUTINE RESIG
C  REDEFINES SURFACE SHAPES USING CRITICAL STREAMLINE METHODOLOGY.
C
        READ (22,*) AVTHK
        READ (22,*) SLFAC
        READ (22,*) CMPRES
        READ (22,*) DPOTMIN
	WRITE (*,*) AVTHK,SLFAC,CMPRES,DPOTMIN
C
C  	CONSTANTS USED FOR INTERPOLATION -- D2MIN IS THE MINIMUM 
C       DISTANCE ALLOWED IN THE INVERSE WEIGHTING DENOMINATOR.  HT2DIS 
C       DEFINES THE RELATIVE IMPORT OF CHANGES IN ELEVATION VERSUS 
C       HORIZONTAL DISTANCE IN THE INVERSE DISTANCE WEIGHTING.  WHEN 
C       SET TO ZERO, VERTICAL TERRAIN EFFECT IS NOT INCLUDED.
C
C       READ ROUGHNESS LENGTH (ZZERO) AND ANEMOMETER HEIGHT (Z10)
C
        READ (22,*) ZZERO,Z10
	Z0=ZZERO
	ZCHOOZ(1)=Z10
        READ (22,*) D2MIN
        READ (22,*) DTWT
C
C       NITER IS THE UPPER LIMIT ON ITERATIONS TOWARD NONDIVERGENCE IN 
C       BAL5 ADJMAX IS THE FRACTION OF THE USUAL ITERATIVE ADJUSTMENT 
C       TOWARD NONDIVERGENCE THAT IS MADE AT GRID POINTS NEAR 
C       OBSERVATIONS IN SUBROUTINE BAL5.
C
        READ (22,*) NITER
        READ (22,*) ADJMAX
	WRITE (*,*) D2MIN,DTWT,NITER,ADJMAX
C
C  READ INDICES OF LOW POINTS TO BE USED IN CRITICAL STREAMLINE 
C  CALCULATIONS FOR EACH TEMPERATURE SOUNDING.
C
	DO 97 LOWS=1,5 
	   READ (22,*) LOWIX(LOWS),LOWIY(LOWS)
97	CONTINUE
C
        READ (22,*) NEND
	WRITE (*,*) 'number of files to do ', NEND
C
C  EXTRA VARIABLES TO OUTPUT -- VERTICAL MOTION (W), THETA
C
	READ(22,*) DOWCMP
	READ(22,*) DOTHET
	READ(22,*) DOPRES
	READ(22,*) DOBRI
	READ(22,*) DOBVPD
C
C  DISABLED PROFILES & TIME SERIES INSTEAD OF ARRAYS
C****************************************************
C
C       READ (22,*) DOWVSZ
C       READ (22,*) NPFYLS
	DOWVSZ=.FALSE.
	NPFYLS=0
	IF (NPFYLS.GT.NWNDPT .AND. DOWVSZ) THEN
	   WRITE(*,*) NPFYLS,' IS TOO MANY WIND PROFILE OUTPUTS!'
	   STOP
	END IF
C****************************************************
	IF (.NOT. DOWVSZ) THEN
	   NPFYLS=0
	ELSE
	   IF (NEND.GT.111) THEN
	      WRITE (*,*) 'TOO MANY CASES FOR PROFILE PLOTS.  ',
     $             'MUST BE 111 OR FEWER.'
     	      STOP
	   END IF
	   DO 107 IT=1,NPFYLS
	      READ (22,*)  PTUTMX,PTUTMY
	      JPRYLX(IT)=1+NINT((PTUTMX-XORIG)/DSCRS)
	      JPRYLY(IT)=1+NINT((PTUTMY-YORIG)/DSCRS)
107	   CONTINUE
	END IF
C
6002	FORMAT (A7)
6006	FORMAT (1X, 20F10.2)
6011	FORMAT (1X, 'SIGMAS: ',20F8.4)
C
	RETURN
C
        END

