C*********************************************************************
         SUBROUTINE TOPO
C*********************************************************************
C
C   READ  AND  COMPUTE TOPOGRAPHY AT GRID POINTS.  GET
C   FIRST GUESS FLOW SURFACES.  RESIG WILL BE USED LATER TO DEFINE THEM
C   IN TERMS OF THE CRITICAL STREAMLINE PARAMETERS. 
C
	INCLUDE 'NGRIDS.PAR'       
C
	INCLUDE 'ANCHOR.CMM'
	INCLUDE 'FLOWER.CMM'
	INCLUDE 'LIMITS.CMM'
C
C  MAKE SURE THAT  THINGS READ ON 1ST PASS ARE THERE ON LATER CALLS
C
        SAVE
C
C  READ TERRAIN HEIGHT VALUES AT GRID POINTS IN METERS, ALL GRIDS
C
	WRITE (*,*) 'READ TOPORAPHY'
	SFCLOW=1.E6
	SFCHI=-1.E6
C
C  IN DATA FILE, NORTHERN ROW IS FIRST.
C  READ HEIGHTS AT GRID POINTS & SET INITIAL BOUNDARY LAYER HT.
C  USE TERRAIN FOLLOWING 1ST; WILL RESET IN RESIG LATER.
C
	DO 28 JINVY=1,NROW
	   JY=1+NROW-JINVY

	   READ (11,6004) (SFCHT(IX,JY),IX=1,NCOL)
	   IF (MOD(JINVY,10).EQ.1) 
     $          WRITE (*,6004) (SFCHT(IX,JY),IX=1,NCOL,10)
C
C  GET ELEVATION AT ORIGIN
C
	  ZORIG=SFCHT(1,1)
          DO 18 IX=1,NCOL
            IF(SFCHT(IX,JY).LT.SFCLOW) SFCLOW=SFCHT(IX,JY)
            IF(SFCHT(IX,JY).GT. SFCHI) SFCHI =SFCHT(IX,JY)
18	  CONTINUE
28	CONTINUE
C
        ZRISE=SFCHI-SFCLOW
        RELHT=AVTHK
C
C GET HEIGHT OF EACH 1ST GUESS SURFACE RELATIVE TO TERRAIN FOR EACH 
C GRID PT.  CHANGE IN HT RELATIVE TO THE LOWEST HT (MSL) IS ASSUMED 
C PROPORTIONAL TO SIGMA FOR THAT SFC.
C
	DO 67 JY=1,NROW
           DO 67 IX=1,NCOL
              DO 65 KZ=1,NLVL
C
		 RHS(IX,JY,KZ) =SIGMA(KZ)*AVTHK- 
     $                   (SFCHT(IX,JY)-SFCLOW)*(1.0-SLFAC)
65         CONTINUE
67	CONTINUE
C
6001    FORMAT(F3.0,107F4.0)
6002    FORMAT (1X, 45F5.0)
6003    FORMAT (1X, 161F5.0)
6004    FORMAT (1X, 180F5.0)
C
      	RETURN
C
      	END

