C********************************************************************
  	REAL FUNCTION DUBYOU(UT,VT,I,J,K)
C********************************************************************
C
C  GETTING VERTICAL MOTION W FROM HORIZONTAL MOTION & FLOW SFC SLOPE. 
C		F LUDWIG 11/89
C
C  REVISED AS A FUNCTION 3/2000
C
          INCLUDE 'NGRIDS.PAR'
C
          INCLUDE 'ANCHOR.CMM'
          INCLUDE 'FLOWER.CMM'
          INCLUDE 'LIMITS.CMM'
C
	SAVE
C
C  GETTING FLOW SURFACE SLOPE
C
	IF (K.GT.1) THEN
	   IF (RHS(I,J,K).GT.0.0) THEN
C
C  CHECK TO SEE IF WE ARE AT EAST OR WEST EDGE, THEN GET FLOW SURFACE 
C  HEIGHTS TO EAST & WEST OF THIS PT.  HTS ABOVE SFC (RHS)
C  ARE ADDED TO SFCHT TO GET MSL HT.  SURFACE HEIGHT IS USED FOR
C  1ST LEVEL (K=1) WHICH REPRESENTS ANEMOMETER HEIGHT WINDS.
C
C
	      IF (I.GT.1 .AND. I.LT.NCOL) THEN
	         DGRIDX=2000.0*DSCRS
	         ZP10=MAX(RHS(I+1,J,K),0.0)
	         ZM10=MAX(RHS(I-1,J,K),0.0)
	         ZP10=0.0
	         ZM10=0.0
	         HSIGE=SFCHT(I+1,J)+ZP10
	         HSIGW=SFCHT(I-1,J)+ZM10
C
C  USE ADJACENT PTS IF AT EDGE
C
	      ELSE IF (I.EQ.1) THEN
	         DGRIDX=1000.0*DSCRS
		 ZP10=MAX(RHS(I+1,J,K),0.0)
		 ZM10=MAX(RHS(I,J,K),0.0)
		 HSIGE=SFCHT(I+1,J)+ZP10
		 HSIGW=SFCHT(I,J)+ZM10
	      ELSE IF (I.EQ.NCOL) THEN
	         DGRIDX=1000.0*DSCRS
		 ZP10=MAX(RHS(I,J,K),0.0)
		 ZM10=MAX(RHS(I-1,J,K),0.0)
		 HSIGE=SFCHT(I,J)+ZP10
		 HSIGW=SFCHT(I-1,J)+ZM10
	      END IF
C
C  NOW DO THE SAME FOR  NORTH SOUTH
C
	      IF (J.GT.1 .AND. J.LT.NROW) THEN
	         DGRIDY=2000.0*DSCRS
	         Z0P1=MAX(RHS(I,J+1,K),0.0)
	         Z0M1=MAX(RHS(I,J-1,K),0.0)
	         HSIGN=SFCHT(I,J+1)+Z0P1
	         HSIGS=SFCHT(I,J-1)+Z0M1
C
C  USE ADJACENT PTS IF AT EDGE
C
	      ELSE IF (J.EQ.1) THEN
	         DGRIDY=1000.0*DSCRS
		 Z0P1=MAX(RHS(I,J+1,K),0.0)
		 Z0M1=MAX(RHS(I,J,K),0.0)
		 HSIGN=SFCHT(I,J+1)+Z0P1
		 HSIGS=SFCHT(I,J)+Z0M1
	      ELSE IF (J.EQ.NROW) THEN
	         DGRIDY=1000.0*DSCRS
	         Z0P1=MAX(RHS(I,J,K),0.0)
	         Z0M1=MAX(RHS(I,J-1,K),0.0)
	         HSIGN=SFCHT(I,J)+Z0P1
	         HSIGS=SFCHT(I,J-1)+Z0M1
	      END IF
C
C  NOW GET W-E & S-N SLOPES
C
	      DHDX=(HSIGE-HSIGW)/DGRIDX
	      DHDY=(HSIGN-HSIGS)/DGRIDY
C
C  VERTICAL MOTION IS INNER PRODUCT OF HORIZ WIND & HT GRADIENT
C  AT ABOVE GROUND PTS.
C
	      DUBYOU=UT*DHDX+VT*DHDY
C
	   ELSE
C
C  VERTICAL MOTION IS ZERO FOR BELOW GROUND PTS
C
	      DUBYOU=0.0
C
	   END IF
C
C  USE SFC HTS TO GET VERTICAL MOTION IN 1ST (ANEMOMETER HT) LAYER
C
	ELSE
	   IF (I.GT.1 .AND. I.LT.NCOL) THEN
	      DGRIDX=2000.0*DSCRS
	      HSIGE=SFCHT(I+1,J)
	      HSIGW=SFCHT(I-1,J)
C
C  USE ADJACENT PTS IF AT EDGE
C
	   ELSE IF (I.EQ.1) THEN
	      DGRIDX=1000.0*DSCRS
	      HSIGE=SFCHT(I+1,J)
	      HSIGW=SFCHT(I,J)
	   ELSE IF (I.EQ.NCOL) THEN
	      DGRIDX=1000.0*DSCRS
	      HSIGE=SFCHT(I,J)
	      HSIGW=SFCHT(I-1,J)
	   END IF
C
C  NOW DO THE SAME FOR  NORTH SOUTH
C
	   IF (J.GT.1 .AND. J.LT.NROW) THEN
	      DGRIDY=2000.0*DSCRS
	      HSIGN=SFCHT(I,J+1)
	      HSIGS=SFCHT(I,J-1)
C
C  USE ADJACENT PTS IF AT EDGE
C
	   ELSE IF (J.EQ.1) THEN
	      DGRIDY=1000.0*DSCRS
	      HSIGN=SFCHT(I,J+1)+Z0P1
	      HSIGS=SFCHT(I,J)+Z0M1
	   ELSE IF (J.EQ.NROW) THEN
	      DGRIDY=1000.0*DSCRS
	      HSIGN=SFCHT(I,J)+Z0P1
	      HSIGS=SFCHT(I,J-1)+Z0M1
	   END IF
C
C  NOW GET W-E & S-N SLOPES
C
	   DHDX=(HSIGE-HSIGW)/DGRIDX
	   DHDY=(HSIGN-HSIGS)/DGRIDY
C
C  VERTICAL MOTION IS INNER PRODUCT OF HORIZ WIND & HT GRADIENT
C  OF SFC HTS.
C
	   DUBYOU=UT*DHDX+VT*DHDY
C
	END IF
C
	RETURN
C
	END

